# version: '3'
# services:

#   nginx:
#     build: requirements/nginx
#     image: nginx
#     container_name: nginx
#     ports:
#       - "443:443"
#     restart: always
#     networks:
#       - docker_network

#   networks:
#     docker_network:

version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped #check always
    expose:
      - 3306
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped #check always
    expose:
      - 9000
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure #check always
volumes:
    wordpress:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/cfiliber/data/wordpress'
    mariadb_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/cfiliber/data/mariadb'
networks:
    inception:
      driver: bridge
